"""empty message

Revision ID: 11cb4ab0e684
Revises: ada17d3eb392
Create Date: 2019-06-21 10:07:38.940763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11cb4ab0e684'
down_revision = 'ada17d3eb392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sv_groups_groupName', table_name='sv_groups')
    op.drop_table('sv_groups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sv_groups',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('groupName', mysql.VARCHAR(collation='utf8_unicode_ci', length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_sv_groups_groupName', 'sv_groups', ['groupName'], unique=True)
    # ### end Alembic commands ###
