"""empty message

Revision ID: 22c3df548a77
Revises: 7b6f3309d8d6
Create Date: 2019-06-21 09:44:11.965413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22c3df548a77'
down_revision = '7b6f3309d8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sv_hosts_ibfk_1', 'sv_hosts', type_='foreignkey')
    op.drop_column('sv_hosts', 'sv_group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sv_hosts', sa.Column('sv_group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='关联组,多对一'))
    op.create_foreign_key('sv_hosts_ibfk_1', 'sv_hosts', 'sv_groups', ['sv_group_id'], ['id'])
    # ### end Alembic commands ###
