"""empty message

Revision ID: 66176ec42974
Revises: 
Create Date: 2019-04-29 09:24:47.615343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66176ec42974'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sv_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('groupName', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sv_groups_groupName'), 'sv_groups', ['groupName'], unique=True)
    op.create_table('sv_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nodeName', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sv_nodes_nodeName'), 'sv_nodes', ['nodeName'], unique=True)
    op.create_table('sv_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('avatar', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('weixin_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('is_del', sa.Boolean(), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('last_modify', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('weixin_name')
    )
    op.create_table('sv_hosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(length=120), nullable=False),
    sa.Column('host_ip', sa.String(length=120), nullable=True),
    sa.Column('sv_port', sa.Boolean(), nullable=True),
    sa.Column('is_del', sa.Boolean(), nullable=True),
    sa.Column('sv_group_id', sa.Integer(), nullable=True),
    sa.Column('sv_node_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sv_group_id'], ['sv_groups.id'], ),
    sa.ForeignKeyConstraint(['sv_node_id'], ['sv_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_index(op.f('ix_sv_hosts_host_ip'), 'sv_hosts', ['host_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sv_hosts_host_ip'), table_name='sv_hosts')
    op.drop_table('sv_hosts')
    op.drop_table('sv_users')
    op.drop_index(op.f('ix_sv_nodes_nodeName'), table_name='sv_nodes')
    op.drop_table('sv_nodes')
    op.drop_index(op.f('ix_sv_groups_groupName'), table_name='sv_groups')
    op.drop_table('sv_groups')
    # ### end Alembic commands ###
