"""empty message

Revision ID: 6dbe073e0ce1
Revises: a59c6c034284
Create Date: 2019-06-20 20:46:20.967353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6dbe073e0ce1'
down_revision = 'a59c6c034284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sv_hosts', sa.Column('host_inner_ip', sa.String(length=120), nullable=True, comment='主机内网ip'))
    op.add_column('sv_hosts', sa.Column('host_public_ip', sa.String(length=120), nullable=True, comment='主机公网ip'))
    op.create_index(op.f('ix_sv_hosts_host_inner_ip'), 'sv_hosts', ['host_inner_ip'], unique=False)
    op.create_index(op.f('ix_sv_hosts_host_public_ip'), 'sv_hosts', ['host_public_ip'], unique=False)
    op.drop_index('ix_sv_hosts_host_ip', table_name='sv_hosts')
    op.drop_column('sv_hosts', 'host_ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sv_hosts', sa.Column('host_ip', mysql.VARCHAR(collation='utf8_unicode_ci', length=120), nullable=True, comment='主机ip'))
    op.create_index('ix_sv_hosts_host_ip', 'sv_hosts', ['host_ip'], unique=False)
    op.drop_index(op.f('ix_sv_hosts_host_public_ip'), table_name='sv_hosts')
    op.drop_index(op.f('ix_sv_hosts_host_inner_ip'), table_name='sv_hosts')
    op.drop_column('sv_hosts', 'host_public_ip')
    op.drop_column('sv_hosts', 'host_inner_ip')
    # ### end Alembic commands ###
