"""empty message

Revision ID: 7b6f3309d8d6
Revises: 6dbe073e0ce1
Create Date: 2019-06-21 09:39:17.718701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b6f3309d8d6'
down_revision = '6dbe073e0ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sv_hosts', sa.Column('ali_instance_id', sa.String(length=120), nullable=False, comment='阿里云实例id'))
    op.add_column('sv_hosts', sa.Column('host_info', sa.String(length=120), nullable=False, comment='主机信息'))
    op.drop_index('info', table_name='sv_hosts')
    op.create_unique_constraint(None, 'sv_hosts', ['ali_instance_id'])
    op.create_unique_constraint(None, 'sv_hosts', ['host_info'])
    op.drop_column('sv_hosts', 'info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sv_hosts', sa.Column('info', mysql.VARCHAR(collation='utf8_unicode_ci', length=120), nullable=False, comment='主机信息'))
    op.drop_constraint(None, 'sv_hosts', type_='unique')
    op.drop_constraint(None, 'sv_hosts', type_='unique')
    op.create_index('info', 'sv_hosts', ['info'], unique=True)
    op.drop_column('sv_hosts', 'host_info')
    op.drop_column('sv_hosts', 'ali_instance_id')
    # ### end Alembic commands ###
