"""empty message

Revision ID: 94702245181d
Revises: 
Create Date: 2019-06-20 15:34:07.188448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94702245181d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sv_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False, comment='服务名称'),
    sa.Column('service_start_cmd', sa.String(length=120), nullable=True, comment='服务启动命令'),
    sa.Column('devops_user_id', sa.Integer(), nullable=True, comment='关联用户,多对一'),
    sa.Column('is_del', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.ForeignKeyConstraint(['devops_user_id'], ['sv_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sv_services_service_name'), 'sv_services', ['service_name'], unique=True)
    op.create_index(op.f('ix_sv_services_service_start_cmd'), 'sv_services', ['service_start_cmd'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sv_services_service_start_cmd'), table_name='sv_services')
    op.drop_index(op.f('ix_sv_services_service_name'), table_name='sv_services')
    op.drop_table('sv_services')
    # ### end Alembic commands ###
