"""empty message

Revision ID: 9c853a99ebb5
Revises: 
Create Date: 2019-07-04 11:39:26.828290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c853a99ebb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sv_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nodeName', sa.String(length=120), nullable=False, comment='节点名称'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sv_nodes_nodeName'), 'sv_nodes', ['nodeName'], unique=True)
    op.create_table('sv_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False, comment='服务名称'),
    sa.Column('service_deploy_dir', sa.String(length=120), nullable=False, comment='服务部署路径'),
    sa.Column('service_detail', sa.String(length=120), nullable=False, comment='服务详情描述'),
    sa.Column('service_start_cmd', sa.String(length=120), nullable=True, comment='服务启动命令'),
    sa.Column('service_ports', sa.String(length=120), nullable=True, comment='服务端口号'),
    sa.Column('is_del', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sv_services_service_deploy_dir'), 'sv_services', ['service_deploy_dir'], unique=False)
    op.create_index(op.f('ix_sv_services_service_detail'), 'sv_services', ['service_detail'], unique=False)
    op.create_index(op.f('ix_sv_services_service_name'), 'sv_services', ['service_name'], unique=True)
    op.create_index(op.f('ix_sv_services_service_ports'), 'sv_services', ['service_ports'], unique=False)
    op.create_index(op.f('ix_sv_services_service_start_cmd'), 'sv_services', ['service_start_cmd'], unique=False)
    op.create_table('sv_userGroups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sv_hosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(length=120), nullable=False, comment='主机名称'),
    sa.Column('host_info', sa.String(length=120), nullable=False, comment='主机信息'),
    sa.Column('ali_instance_id', sa.String(length=120), nullable=False, comment='阿里云实例id'),
    sa.Column('host_inner_ip', sa.String(length=120), nullable=True, comment='主机内网ip'),
    sa.Column('host_public_ip', sa.String(length=120), nullable=True, comment='主机公网ip'),
    sa.Column('sv_port', sa.Integer(), nullable=True, comment='主机ssh端口'),
    sa.Column('is_del', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.Column('sv_node_id', sa.Integer(), nullable=True, comment='关联节点,多对一'),
    sa.ForeignKeyConstraint(['sv_node_id'], ['sv_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ali_instance_id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_index(op.f('ix_sv_hosts_host_inner_ip'), 'sv_hosts', ['host_inner_ip'], unique=False)
    op.create_index(op.f('ix_sv_hosts_host_public_ip'), 'sv_hosts', ['host_public_ip'], unique=False)
    op.create_table('sv_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roleName', sa.String(length=120), nullable=False, comment='角色名称'),
    sa.Column('sv_userGroup_Id', sa.Integer(), nullable=True, comment='用户组权限外键'),
    sa.ForeignKeyConstraint(['sv_userGroup_Id'], ['sv_userGroups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sv_roles_roleName'), 'sv_roles', ['roleName'], unique=True)
    op.create_table('sv_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True, comment='用户名'),
    sa.Column('avatar', sa.String(length=120), nullable=True, comment='头像'),
    sa.Column('email', sa.String(length=120), nullable=True, comment='邮箱'),
    sa.Column('weixin_name', sa.String(length=120), nullable=True, comment='微信昵称'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号'),
    sa.Column('is_del', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('last_modify', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('userGroup_Id', sa.Integer(), nullable=True, comment='关联一级用户组,多对一'),
    sa.ForeignKeyConstraint(['userGroup_Id'], ['sv_userGroups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('weixin_name')
    )
    op.create_table('services_developers',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['sv_services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sv_users.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'user_id')
    )
    op.create_table('services_hosts',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['sv_hosts.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['sv_services.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'host_id')
    )
    op.create_table('sv_navs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('navTitle', sa.String(length=120), nullable=False, comment='一级导航栏标题'),
    sa.Column('navUrl', sa.String(length=120), nullable=True, comment='一级导航栏url'),
    sa.Column('navType', sa.Boolean(), nullable=True, comment='导航栏分类,默认为后台导航栏'),
    sa.Column('is_del', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='关联角色,多对一'),
    sa.ForeignKeyConstraint(['role_id'], ['sv_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('navTitle')
    )
    op.create_index(op.f('ix_sv_navs_navUrl'), 'sv_navs', ['navUrl'], unique=False)
    op.create_table('sv_subnavs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False, comment='二级导航栏标题'),
    sa.Column('nav_url', sa.String(length=200), nullable=False, comment='二级导航栏url'),
    sa.Column('nav_Id', sa.Integer(), nullable=True, comment='关联一级导航栏,多对一'),
    sa.Column('is_del', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.ForeignKeyConstraint(['nav_Id'], ['sv_navs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sv_subnavs_nav_url'), 'sv_subnavs', ['nav_url'], unique=True)
    op.create_index(op.f('ix_sv_subnavs_title'), 'sv_subnavs', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sv_subnavs_title'), table_name='sv_subnavs')
    op.drop_index(op.f('ix_sv_subnavs_nav_url'), table_name='sv_subnavs')
    op.drop_table('sv_subnavs')
    op.drop_index(op.f('ix_sv_navs_navUrl'), table_name='sv_navs')
    op.drop_table('sv_navs')
    op.drop_table('services_hosts')
    op.drop_table('services_developers')
    op.drop_table('sv_users')
    op.drop_index(op.f('ix_sv_roles_roleName'), table_name='sv_roles')
    op.drop_table('sv_roles')
    op.drop_index(op.f('ix_sv_hosts_host_public_ip'), table_name='sv_hosts')
    op.drop_index(op.f('ix_sv_hosts_host_inner_ip'), table_name='sv_hosts')
    op.drop_table('sv_hosts')
    op.drop_table('sv_userGroups')
    op.drop_index(op.f('ix_sv_services_service_start_cmd'), table_name='sv_services')
    op.drop_index(op.f('ix_sv_services_service_ports'), table_name='sv_services')
    op.drop_index(op.f('ix_sv_services_service_name'), table_name='sv_services')
    op.drop_index(op.f('ix_sv_services_service_detail'), table_name='sv_services')
    op.drop_index(op.f('ix_sv_services_service_deploy_dir'), table_name='sv_services')
    op.drop_table('sv_services')
    op.drop_index(op.f('ix_sv_nodes_nodeName'), table_name='sv_nodes')
    op.drop_table('sv_nodes')
    # ### end Alembic commands ###
