"""empty message

Revision ID: a59c6c034284
Revises: a7536e0de4d2
Create Date: 2019-06-20 19:42:39.044161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a59c6c034284'
down_revision = 'a7536e0de4d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sv_hosts', sa.Column('info', sa.String(length=120), nullable=False, comment='主机信息'))
    op.alter_column('sv_hosts', 'sv_port',
               existing_type=mysql.TINYINT(display_width=1),
               comment='主机ssh端口',
               existing_comment='主机supervisor端口',
               existing_nullable=True)
    op.create_unique_constraint(None, 'sv_hosts', ['info'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sv_hosts', type_='unique')
    op.alter_column('sv_hosts', 'sv_port',
               existing_type=mysql.TINYINT(display_width=1),
               comment='主机supervisor端口',
               existing_comment='主机ssh端口',
               existing_nullable=True)
    op.drop_column('sv_hosts', 'info')
    # ### end Alembic commands ###
