"""empty message

Revision ID: a7536e0de4d2
Revises: c713f89bcfd7
Create Date: 2019-06-20 15:39:54.682138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7536e0de4d2'
down_revision = 'c713f89bcfd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sv_services', sa.Column('deploy_host_id', sa.Integer(), nullable=True, comment='关联主机,多对一'))
    op.create_foreign_key(None, 'sv_services', 'sv_hosts', ['deploy_host_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sv_services', type_='foreignkey')
    op.drop_column('sv_services', 'deploy_host_id')
    # ### end Alembic commands ###
