"""empty message

Revision ID: c713f89bcfd7
Revises: 94702245181d
Create Date: 2019-06-20 15:37:00.289130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c713f89bcfd7'
down_revision = '94702245181d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sv_services', sa.Column('deploy_dir', sa.String(length=120), nullable=False, comment='服务部署路径'))
    op.create_index(op.f('ix_sv_services_deploy_dir'), 'sv_services', ['deploy_dir'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sv_services_deploy_dir'), table_name='sv_services')
    op.drop_column('sv_services', 'deploy_dir')
    # ### end Alembic commands ###
